In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1) #Columns

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0) #Rows

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1) #become dataframe

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2']) #Inserting keys

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [12]:
dframe1

X         Y         Z
0  0.813738  0.360781  0.968193
1 -0.831081  1.378975 -0.586226
2  0.709317  0.448473 -0.533138
3  0.276628  2.404449 -1.420564

In [13]:
dframe2

Y         Q         X
0 -0.744688 -0.399197 -1.438507
1 -0.938061 -0.129735 -0.224467
2  0.614556 -0.738693 -0.132897

In [14]:
pd.concat([dframe1,dframe2]) #index will repeat for 0,1,2,3,0,1,2

X         Y         Z         Q
0  0.813738  0.360781  0.968193       NaN
1 -0.831081  1.378975 -0.586226       NaN
2  0.709317  0.448473 -0.533138       NaN
3  0.276628  2.404449 -1.420564       NaN
0 -1.438507 -0.744688       NaN -0.399197
1 -0.224467 -0.938061       NaN -0.129735
2 -0.132897  0.614556       NaN -0.738693

In [15]:
pd.concat([dframe1,dframe2],ignore_index=True) # index will go from 0 to 6

X         Y         Z         Q
0  0.813738  0.360781  0.968193       NaN
1 -0.831081  1.378975 -0.586226       NaN
2  0.709317  0.448473 -0.533138       NaN
3  0.276628  2.404449 -1.420564       NaN
4 -1.438507 -0.744688       NaN -0.399197
5 -0.224467 -0.938061       NaN -0.129735
6 -0.132897  0.614556       NaN -0.738693